---
- name: Configure gateway
  hosts: gateway
  become: yes
  vars_files:
    - psk.yml
  tasks:
    - name: Update and dist-upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist
      when: false

    - name: Install StrongSwan
      apt:
        name: strongswan
        state: present

    - name: Configure StrongSwan with ipsec.conf
      copy:
        content: |
          config setup
            charondebug="cfg 4, dmn 4, ike 4, net 4"
            # charondebug="ike 3, knl 1, cfg 3"
            uniqueids=replace

          conn gateway-to-server
            auto=add
            compress=no
            type=tunnel
            keyexchange=ikev2
            fragmentation=yes
            forceencaps=yes
            dpdaction=clear
            dpddelay=30s
            dpdtimeout=180s
            rekey=yes
            authby=secret
            ike=aes256gcm12-sha256-modp4096,aes128gcm12-sha256-modp4096!
            esp=aes256gcm12-sha256,aes128gcm12-sha256!
            left=192.168.20.2
            leftid=@gateway
            leftsubnet=0.0.0.0/0
            leftsourceip=10.8.0.1
            right=%any
            rightid=@server
            rightsourceip=10.8.0.2/32
            mobike=no
        dest: /etc/ipsec.conf
        owner: root
        group: root
        mode: '0644'

    - name: Configure IPsec secrets
      copy:
        content: |
          @gateway @server : PSK "{{ vpn_psk }}"
        dest: /etc/ipsec.secrets
        owner: root
        group: root
        mode: '0600'

    - name: Enable and start StrongSwan
      systemd:
        name: strongswan
        enabled: yes
        state: restarted

    - name: Enable IP forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: yes
        state: present
        reload: yes

    - name: Configure IPTables for NAT
      iptables:
        table: nat
        chain: PREROUTING
        protocol: tcp
        destination_port: 80
        jump: DNAT
        to_destination: "10.8.0.2"
      notify: Save IPTables

    - name: Configure IPTables for masquerading
      iptables:
        table: nat
        chain: POSTROUTING
        jump: MASQUERADE
      notify: Save IPTables

    - name: Allow forwarding of HTTP traffic
      iptables:
        table: filter
        chain: FORWARD
        protocol: tcp
        destination_port: 80
        jump: ACCEPT
      notify: Save IPTables

    - meta: flush_handlers

    - name: Provision complete
      debug:
        msg: "Gateway machine (StrongSwan VPN server and traffic forwarder) provisioned."
  
  handlers:
    - name: Save IPTables
      community.general.iptables_state:
        state: saved
        path: /etc/iptables/rules.v4