---
- name: Configure remote (Nginx web server)
  hosts: remote
  become: yes
  tasks:
    - name: Update and dist-upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Provision complete
      debug:
        msg: "Remote machine (Nginx web server) provisioned."
