---
- name: Configure remote
  hosts: remote
  become: yes
  tasks:
    - name: Update and dist-upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Provision complete
      debug:
        msg: "Remote machine provisioned."
