---
- name: Install iptables and iptables-persistent
  apt:
    name: 
    - iptables
    - iptables-persistent
    state: present

- name: Enable IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- name: Flush all iptables rules
  iptables:
    table: "{{ item }}"
    flush: yes
  with_items:
  - filter
  - nat

- name: Set default policies
  iptables:
    chain: "{{ item.chain }}"
    policy: "{{ item.policy }}"
  with_items:
  - { chain: INPUT, policy: ACCEPT }
  - { chain: FORWARD, policy: ACCEPT }
  - { chain: OUTPUT, policy: ACCEPT }

- name: Allow all loopback traffic
  iptables:
    chain: INPUT
    in_interface: lo
    jump: ACCEPT

- name: Drop traffic to 127/8 that doesn't use lo0
  iptables:
    chain: INPUT
    destination: 127.0.0.0/8
    jump: REJECT

- name: Allow established and related traffic on INPUT chain
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

- name: Allow established and related traffic on FORWARD chain
  iptables:
    chain: FORWARD
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

- name: Allow SSH
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 22
    jump: ACCEPT

- name: Allow internal network traffic from lan_net to wan_net
  iptables:
    chain: FORWARD
    in_interface: enp0s8
    out_interface: enp0s9
    source: 192.168.10.0/24
    destination: 192.168.20.0/24
    jump: ACCEPT

- name: Add iptables rules for forwarding LAN to general WAN
  iptables:
    chain: FORWARD
    in_interface: enp0s8 
    out_interface: enp0s3
    jump: ACCEPT
    
- name: Add masquerade rule for lan_net to wan_net
  iptables:
    table: nat
    chain: POSTROUTING
    out_interface: enp0s9
    source: 192.168.10.0/24
    destination: 192.168.20.0/24
    jump: MASQUERADE

- name: Add masquerade rule for all outgoing traffic on enp0s3
  iptables:
    table: nat
    chain: POSTROUTING
    out_interface: enp0s3
    jump: MASQUERADE


- name: Save current state of the firewall in system file
  community.general.iptables_state:
    state: saved
    path: /etc/iptables/rules.v4
