---
- name: Configure server
  hosts: server
  become: yes
  tasks:
    - name: Delete existing default route
      command: ip route del default
      ignore_errors: yes

    - name: Add default route to router
      command: ip route add default via 192.168.10.1

    - name: Provision complete
      debug:
        msg: "Server machine provisioned and routing through Router."
