---
# Drop Strongswan connection if it exists
- name: Check if Strongswan connection exists
  shell: ipsec statusall | grep -q 'gateway-to-server'
  register: strongswan_connection_exists
  ignore_errors: true

- name: Drop Strongswan connection if it exists
  shell: ipsec down rw-psk
  when: strongswan_connection_exists.rc == 0
  ignore_errors: true

- name: Update and dist-upgrade apt packages
  apt:
    update_cache: yes
    upgrade: dist

- name: Install packages
  apt:
    name: 
      - nginx
      - strongswan
    state: present

- name: Create a simple HTML page
  copy:
    content: |
      <html>
      <head>
          <title>Welcome to the Server</title>
      </head>
      <body>
          <h1>Hello from the Server!</h1>
      </body>
      </html>
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: '0644'

- name: Start and enable Nginx
  systemd:
    name: nginx
    enabled: yes
    state: started

- name: Configure StrongSwan with ipsec.conf
  template:
    src: ipsec.conf.server.j2
    dest: /etc/ipsec.conf
    owner: root
    group: root
    mode: '0644'

- name: Configure IPsec secrets
  copy:
    content: |
      @server @gateway : PSK "{{ vpn_psk }}"
    dest: /etc/ipsec.secrets
    owner: root
    group: root
    mode: '0600'

- name: Restart StrongSwan service
  systemd:
    name: strongswan-starter
    enabled: yes
    state: restarted

- name: Deploy gateway check script
  copy:
    src: files/check_gateway.sh
    dest: /usr/local/bin/check_gateway.sh
    owner: root
    group: root
    mode: '0755'

- name: Set up cron job for gateway check
  cron:
    name: "Check IPsec connection status"
    minute: "*/5"
    job: "/usr/local/bin/check_gateway.sh"

- name: Deploy logrotate configuration for gateway check log
  copy:
    content: |
      /var/log/gateway_check.log {
          daily
          missingok
          rotate 7
          compress
          delaycompress
          notifempty
          create 0640 root adm
          sharedscripts
          postrotate
              /usr/bin/systemctl reload rsyslog > /dev/null 2>&1 || true
          endscript
      }
    dest: /etc/logrotate.d/gateway_check
    owner: root
    group: root
    mode: '0644'